### ISSUE TITLE
BrowserBruter Installation

### ISSUE THREAD

**Issue by Samratc030** [netsquare/BrowserBruter#3]
I was facing difficulties in installing the BrowserBruter on my Linux machine...
Later on after getting assistance from Jafar Sir, I tried command 'sudo apt install python3-tk' and it ran fine afterwords...
![1](https://github.com/netsquare/BrowserBruter/assets/83419310/f06b14f7-44c6-4e27-84c2-bbbf4747b535)
![2](https://github.com/netsquare/BrowserBruter/assets/83419310/9c3761e6-0e2e-4f8d-afbc-aefa8c2c9009)

**Comment by zinja-coder** [comment]
Hey @Samratc030 You must be facing - `Import Error: No module named 'Tkinter'`. Glad you were able to solve the issue using `sudo apt install python3-tk`.

We will add this into the documentation in next update. Thanks for reaching us out.
