### ISSUE TITLE
Python int too large to convert to C long

### ISSUE THREAD

**Issue by Deathpoolxrs** [netsquare/BrowserBruter#5]
Command: python BrowserBruter.py --elements loginUserName,loginUserPassword --payloads payload.txt --target https://example.com/?grmAccess --button btn-default --attack 1 --debug

Traceback (most recent call last):
  File "C:\Users\<username>\Desktop\BrowserBruter\BrowserBruter.py", line 1850, in <module>
    generate_final_report()
  File "C:\Users\<username>\Desktop\BrowserBruter\BrowserBruter.py", line 1047, in generate_final_report
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long

**Comment by zinja-coder** [comment]
Hey @Deathpoolxrs , Thanks for reaching out. It seems you are using BrowserBruter on Windows Operating System. At present Browser Bruter does not support the Windows based machine. May you kindly provide further details about this for example Are you using windows operating system? Have your tried the same attack from linux machine? Does the same issue present in Linux machine? What is the content of the Error.txt file in linux machine if the same issue is present there? Have you checked the traffic using `--verbose` flag?

Thanks & Regards, Hoping to hear from you soon.

**Comment by zinja-coder** [comment]
Hey @Deathpoolxrs , it's been a week since I heard from you. Can you please provide update.

**Comment by Deathpoolxrs** [comment]
Hey @zinja-coder, 

Yes, I was using it in Windows. It's working perfectly on Kali. Thank you!

**Comment by zinja-coder** [comment]
Closing this as it is resolved.
